import { PricingPlan, PricingFeature } from "@/types";

export const pricingPlans: PricingPlan[] = [
  {
    tier: "free",
    name: "FREE",
    monthlyPrice: 0,
    yearlyPrice: 0,
    widgets: 2,
    apps: 0,
    viewsPerMonth: 100,
    embedOnWebsite: false,
    removeBranding: false,
    betaFeatures: false,
    support: "Email",
    widgetTypes: 7,
    features: ["Buttons, Counters, Productivity widgets"],
  },
  {
    tier: "basic",
    name: "BASIC",
    monthlyPrice: 3,
    yearlyPrice: 29,
    widgets: 15,
    apps: 5,
    viewsPerMonth: 5000,
    embedOnWebsite: false,
    removeBranding: true,
    betaFeatures: false,
    support: "Email",
    widgetTypes: 12,
    features: ["Weather widgets", "Pomodoro & Recurring Tasks"],
  },
  {
    tier: "pro",
    name: "PRO",
    monthlyPrice: 5,
    yearlyPrice: 48,
    widgets: 30,
    apps: 10,
    viewsPerMonth: 50000,
    embedOnWebsite: true,
    removeBranding: true,
    betaFeatures: true,
    support: "Priority Email",
    widgetTypes: 18,
    features: ["Paypal Button, Weather Forecast, KPI", "Embed widgets on website"],
  },
];

export const pricingFeatures: PricingFeature[] = [
  { name: "Embed on Notion pages", key: "embedNotion", values: { free: "Unlimited", basic: "Unlimited", pro: "Unlimited" } },
  { name: "Widgets & Apps", key: "widgetsTotal", values: { free: "2", basic: "15", pro: "30" } },
  { name: "Views per month", key: "viewsPerMonth", values: { free: "100", basic: "5,000", pro: "50,000" } },
  { name: "Embed widgets on website", key: "embedOnWebsite", values: { free: false, basic: false, pro: true } },
  { name: "Removed Branding", key: "removeBranding", values: { free: false, basic: true, pro: true } },
  { name: "Beta Features", key: "betaFeatures", values: { free: false, basic: false, pro: true } },
  { name: "Support", key: "support", values: { free: "Email", basic: "Email", pro: "Priority Email" } },
];
