import { PricingPlan, PricingFeature } from "@/types";

export const pricingPlans: PricingPlan[] = [
  {
    tier: "free",
    name: "FREE",
    monthlyPrice: 0,
    yearlyPrice: 0,
    widgets: 2,
    apps: 0,
    viewsPerMonth: 100,
    embedOnWebsite: false,
    removeBranding: false,
    betaFeatures: false,
    support: "Email",
    widgetTypes: 7,
    features: ["Buttons, Counters, Productivity widgets"],
  },
  {
    tier: "basic",
    name: "BASIC",
    monthlyPrice: 3,
    yearlyPrice: 3 * 12 * 0.8,
    widgets: 30,
    apps: 10,
    viewsPerMonth: 5000,
    embedOnWebsite: false,
    removeBranding: true,
    betaFeatures: false,
    support: "Email",
    widgetTypes: 17,
    features: ["Weather widgets", "Pomodoro & Recurring Tasks"],
  },
  {
    tier: "pro",
    name: "PRO",
    monthlyPrice: 5,
    yearlyPrice: 5 * 12 * 0.8,
    widgets: 70,
    apps: 20,
    viewsPerMonth: 50000,
    embedOnWebsite: true,
    removeBranding: true,
    betaFeatures: true,
    support: "Priority Email",
    widgetTypes: 21,
    features: ["Paypal Button, Weather Forecast, KPI", "Embed widgets on website"],
  },
  {
    tier: "ultimate",
    name: "ULTIMATE",
    monthlyPrice: 7,
    yearlyPrice: 7 * 12 * 0.8,
    widgets: 300,
    apps: 100,
    viewsPerMonth: 250000,
    embedOnWebsite: true,
    removeBranding: true,
    betaFeatures: true,
    support: "Priority Email",
    widgetTypes: 25,
    features: ["Beta Features", "Embed widgets on website"],
  },
];

export const pricingFeatures: PricingFeature[] = [
  { name: "Embed on Notion pages", key: "embedNotion", values: { free: "Unlimited", basic: "Unlimited", pro: "Unlimited", ultimate: "Unlimited" } },
  { name: "Widgets & Apps", key: "widgetsTotal", values: { free: "2", basic: "30", pro: "70", ultimate: "300" } },
  { name: "Views per month", key: "viewsPerMonth", values: { free: "100", basic: "5,000", pro: "50,000", ultimate: "250,000" } },
  { name: "Embed widgets on website", key: "embedOnWebsite", values: { free: false, basic: false, pro: true, ultimate: true } },
  { name: "Removed Branding", key: "removeBranding", values: { free: false, basic: true, pro: true, ultimate: true } },
  { name: "Beta Features", key: "betaFeatures", values: { free: false, basic: false, pro: true, ultimate: true } },
  { name: "Support", key: "support", values: { free: "Email", basic: "Email", pro: "Priority Email", ultimate: "Priority Email" } },
];
