import { WidgetDefinition } from "@/types";

export const widgets: WidgetDefinition[] = [
  // COUNTERS
  {
    id: "project-progress",
    name: "Project Progress",
    slug: "project-progress",
    description: "Track and visualize progress across multiple projects with beautiful progress bars embedded directly in your Notion workspace",
    category: "counters",
    icon: "BarChart3",
    previewUrl: "/widgets/project-progress.svg",
    isNew: true,
    requiredPlan: "free",
    configSchema: [
      { key: "projectName", label: "Project Name", type: "text", default: "My Project" },
      { key: "progress", label: "Progress (%)", type: "number", default: 65 },
      { key: "color", label: "Bar Color", type: "color", default: "#FF6B00" },
    ],
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    slug: "progress-bar",
    description: "Make your deadlines visible with our Progress Bar Widget. Easy to use and embed on your Notion page.",
    category: "counters",
    icon: "Gauge",
    previewUrl: "/widgets/progress-bar.svg",
    isNew: true,
    requiredPlan: "free",
    configSchema: [
      { key: "label", label: "Label", type: "text", default: "Progress" },
      { key: "value", label: "Value (%)", type: "number", default: 75 },
      { key: "color", label: "Color", type: "color", default: "#FF6B00" },
    ],
  },
  {
    id: "habit-counter",
    name: "Habit Counter",
    slug: "habit-counter",
    description: "Track your habits with our Habit Counter widget, helping you stay on top of your goals and build healthy habits.",
    category: "counters",
    icon: "CheckSquare",
    previewUrl: "/widgets/habit-counter.svg",
    requiredPlan: "free",
    configSchema: [
      { key: "habitName", label: "Habit Name", type: "text", default: "Read Daily" },
      { key: "streak", label: "Current Streak", type: "number", default: 12 },
    ],
  },
  {
    id: "kpi",
    name: "KPI Widget",
    slug: "kpi",
    description: "Track your key performance indicators with our KPI widget, helping you monitor and analyze your business metrics with ease.",
    category: "counters",
    icon: "TrendingUp",
    previewUrl: "/widgets/kpi.svg",
    isNew: true,
    requiredPlan: "pro",
    configSchema: [
      { key: "metricName", label: "Metric Name", type: "text", default: "Revenue" },
      { key: "value", label: "Value", type: "text", default: "$12,450" },
      { key: "change", label: "Change (%)", type: "number", default: 12.5 },
    ],
  },
  {
    id: "counter",
    name: "Counter Widget",
    slug: "counter",
    description: "Create a simple counter widget. Customize the look and feel of the counter widget to match your design.",
    category: "counters",
    icon: "PlusCircle",
    previewUrl: "/widgets/counter.svg",
    isNew: true,
    requiredPlan: "free",
    configSchema: [
      { key: "label", label: "Label", type: "text", default: "Count" },
      { key: "initialValue", label: "Start Value", type: "number", default: 0 },
    ],
  },
  {
    id: "page-view",
    name: "Page View",
    slug: "page-view",
    description: "Enhance user experience with our Page View Widget, enabling users to easily track impressions and monitor page performance.",
    category: "counters",
    icon: "Eye",
    previewUrl: "/widgets/page-view.svg",
    isNew: true,
    requiredPlan: "free",
    configSchema: [
      { key: "label", label: "Label", type: "text", default: "Views" },
    ],
  },
  {
    id: "word-clock",
    name: "Word Clock",
    slug: "word-clock",
    description: "Aesthetic Word Clock widget for your Notion Dashboard",
    category: "counters",
    icon: "Clock",
    previewUrl: "/widgets/word-clock.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  {
    id: "year-month-week-day-progress",
    name: "Life, Year, Month, Week and Day Progress",
    slug: "year-month-week-day-progress",
    description: "Create beautiful progress bars for your life, year, month, week and day",
    category: "counters",
    icon: "Calendar",
    previewUrl: "/widgets/life-progress.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  {
    id: "simple-count-down",
    name: "Simple Count Down Timer",
    slug: "simple-count-down",
    description: "Simple Countdown to any Date and Time",
    category: "counters",
    icon: "Timer",
    previewUrl: "/widgets/countdown.svg",
    requiredPlan: "free",
    configSchema: [
      { key: "targetDate", label: "Target Date", type: "text", default: "2026-12-31" },
    ],
  },
  {
    id: "world-clock",
    name: "World Clock",
    slug: "world-clock",
    description: "A simple clock for any timezone",
    category: "counters",
    icon: "Globe",
    previewUrl: "/widgets/world-clock.svg",
    requiredPlan: "free",
    configSchema: [
      { key: "timezone", label: "Timezone", type: "text", default: "UTC" },
    ],
  },
  // BUTTONS
  {
    id: "paypal-button",
    name: "Paypal Purchase Button",
    slug: "paypal-button",
    description: "Integrate a customizable PayPal button widget on your notion or website, allowing customers to click and pay for instant purchases.",
    category: "buttons",
    icon: "CreditCard",
    previewUrl: "/widgets/paypal-button.svg",
    isNew: true,
    requiredPlan: "pro",
    configSchema: [
      { key: "paypalEmail", label: "PayPal Email", type: "text", default: "" },
      { key: "amount", label: "Amount ($)", type: "number", default: 9.99 },
      { key: "itemName", label: "Item Name", type: "text", default: "Digital Product" },
    ],
  },
  {
    id: "button",
    name: "Button Widget",
    slug: "button",
    description: "Effortlessly enhance your Notion docs with our button widget. Click to send emails or link to sites.",
    category: "buttons",
    icon: "MousePointerClick",
    previewUrl: "/widgets/button.svg",
    requiredPlan: "free",
    configSchema: [
      { key: "label", label: "Button Text", type: "text", default: "Click Me" },
      { key: "url", label: "URL", type: "text", default: "https://" },
      { key: "color", label: "Color", type: "color", default: "#FF6B00" },
    ],
  },
  {
    id: "upvote-button",
    name: "Upvote Button",
    slug: "upvote-button",
    description: "Upvote button is a widget that allows visitors to either vote up or down on content within your Notion document or your website.",
    category: "buttons",
    icon: "ThumbsUp",
    previewUrl: "/widgets/upvote.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  {
    id: "like-button",
    name: "Like Button",
    slug: "like-button",
    description: "Allow your users to express their appreciation with this 'Like' button.",
    category: "buttons",
    icon: "Heart",
    previewUrl: "/widgets/like.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  // WEATHER
  {
    id: "weather",
    name: "Weather Forecast",
    slug: "weather",
    description: "Stay ahead with our weather widget: get real-time updates and 10-day forecasts, fully customizable with your choice of colors and icons.",
    category: "weather",
    icon: "CloudSun",
    previewUrl: "/widgets/weather-forecast.svg",
    isNew: true,
    requiredPlan: "pro",
    configSchema: [
      { key: "location", label: "Location", type: "text", default: "New York" },
      { key: "units", label: "Units", type: "select", default: "metric", options: [{ label: "Celsius", value: "metric" }, { label: "Fahrenheit", value: "imperial" }] },
    ],
  },
  {
    id: "weather-round",
    name: "Weather Round",
    slug: "weather-round",
    description: "Weather Round is a simple weather widget for your Notion Dashboard.",
    category: "weather",
    icon: "Sun",
    previewUrl: "/widgets/weather-round.svg",
    requiredPlan: "basic",
    configSchema: [
      { key: "location", label: "Location", type: "text", default: "London" },
    ],
  },
  {
    id: "weather-square",
    name: "Weather Square",
    slug: "weather-square",
    description: "Weather Square is a simple weather widget for your Notion Dashboard.",
    category: "weather",
    icon: "Cloud",
    previewUrl: "/widgets/weather-square.svg",
    requiredPlan: "basic",
    configSchema: [
      { key: "location", label: "Location", type: "text", default: "Tokyo" },
    ],
  },
  // PRODUCTIVITY
  {
    id: "time-tracker",
    name: "Time Tracker",
    slug: "time-tracker",
    description: "Track and visualize time spent on tasks and projects in Notion",
    category: "productivity",
    icon: "Clock",
    previewUrl: "/widgets/time-tracker.svg",
    isNew: true,
    requiredPlan: "pro",
    configSchema: [],
  },
  {
    id: "google-calendar",
    name: "Calendar Widget",
    slug: "google-calendar",
    description: "Connect your Google Calendar and manage your day without switching apps.",
    category: "productivity",
    icon: "CalendarDays",
    previewUrl: "/widgets/calendar.svg",
    isNew: true,
    requiredPlan: "pro",
    configSchema: [],
  },
  {
    id: "todo",
    name: "To-Do List",
    slug: "todo",
    description: "Effortlessly manage tasks in Notion using our To-Do List widget for streamlined task tracking and organization.",
    category: "productivity",
    icon: "ListTodo",
    previewUrl: "/widgets/todo.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  {
    id: "inspirational-quotes",
    name: "Inspirational Quotes",
    slug: "inspirational-quotes",
    description: "Minimalistic Quotes widget for your Notion.",
    category: "productivity",
    icon: "Quote",
    previewUrl: "/widgets/quotes.svg",
    requiredPlan: "free",
    configSchema: [],
  },
  // BUSINESS
  {
    id: "project-progress-biz",
    name: "Project Progress",
    slug: "project-progress",
    description: "Track and visualize progress across multiple projects with beautiful progress bars embedded directly in your Notion workspace",
    category: "business",
    icon: "BarChart3",
    previewUrl: "/widgets/project-progress.svg",
    isNew: true,
    requiredPlan: "free",
    configSchema: [],
  },
];

export function getWidgetBySlug(slug: string): WidgetDefinition | undefined {
  return widgets.find((w) => w.slug === slug);
}

export function getWidgetsByCategory(category: string): WidgetDefinition[] {
  return category === "all" ? widgets : widgets.filter((w) => w.category === category);
}

export const widgetCategories = [
  { id: "all", name: "All", icon: "LayoutGrid" },
  { id: "counters", name: "Counters", icon: "BarChart3" },
  { id: "buttons", name: "Buttons", icon: "MousePointerClick" },
  { id: "weather", name: "Weather", icon: "CloudSun" },
  { id: "productivity", name: "Productivity", icon: "Zap" },
  { id: "business", name: "Business", icon: "Briefcase" },
] as const;
